### ISSUE TITLE
Duplicated data after updating spatial names

### ISSUE THREAD

**Issue by Echisholm21** [casaultb/azmpdata#16]
Attention: @clayton33 @casaultb 

I wanted to create this issue for reference, even though the initial problem is already solved because I think it is highly likely we could see a similar issue again. 

In `Derived_Annual_Broadscale`, there were two distinct occasions where the 'area' metadata was changed.  First it was updated in the original data (from 'Scotion Shelf' to 'Scotian Shelf'). Second, it was updated in the `areas.R` and `coldIntermediateLayer.R` formatting scripts (from 'Scotian Shelf' to 'scotian_shelf_grid' and 'scotian_shelf_box'). 

In both of these cases, when the final package data tables were updated, duplicate data rows were created with the new area names. This resulted in a `Derived_Annual_Broadscale` table with three rows containing the same data point, for example for a density gradient of -0.00139 in 1948, there were three rows, each with area name 'Scotion Shelf', 'Scotian Shelf', or 'scotian_shelf_box'. 

This issue WILL repeat itself with the current data updating system if other area names are changed, either in the original data or in `.r` scripts. Although I believe this will only be an issue in the Physical data and not in the biological data which is updated differently. 

This issue is corrected in Derived_Annual_Broadscale but the updating mechanism should be updated to account for this potential duplication of data in the future. 

Any suggestions on how to best account for this possibility in the update code would be welcome. I think this issue would be best solved by creating a system where biological and physical data are updated in unison, from scratch, each time. But a surface level fix might look like creating a specific function to replace area names in dataframes rather than editing them manually.

**Comment by clayton33** [comment]
I'm kind of confused as to why this is happening. Does the update code append to the previously created data files ?  Maybe you could point me to some code that merges the BO and PO data together and I can have a look.

**Comment by Echisholm21** [comment]
Yes, I may be able to explain it better verbally in our meeting but essentially the `combine_all_data()` code is appending the existing package dataframes with the physical data.

**Comment by clayton33** [comment]
Per our meeting yesterday, it revealed that we had a data flow issue as the PO data is uploaded directly to the package directory on Github, whereas all BO data is put on an ftp site and then called in. Therefore, when the PO data was joined to the BO data, it was simply being appended, which did not wipe out any updates made to the PO data.

In order to better streamline this, all PO data will now be put on the ftp site, and the data will be joined in appropriate scripts. Thus the `data-raw` directory will be deleted, and any PO data previously uploaded to github will be deleted.
