### ISSUE TITLE
where to house functions used to build data

### ISSUE THREAD

**Issue by clayton33** [casaultb/azmpdata#27]
**Summary**
The following functions, and their use,

* `data_update()` - to update the data, used in `inst/extdata/source_all.R`.
* `read.physical()` - to read in physical related data from the ftp site.

currently reside in `R/`, but are used 'internally' in the package. `read.physical()` is fully documented, here documented meaning it has all the roxygen pieces, is used in MANY scripts in `inst/extdata/*` to read in the format that the physical data is provided in, and is currently exported when the package is built. `data_update()` does not have any documentation, but comments note that it is in development.

**Proposal**
*requires vote from all developers* (@casaultb )(@j-harbin and @MMMcMahon - you can vote too if you feel strongly about one or both, also feel free to give some insight if you want as well, or nothing). **Voting will close at noon on Tuesday, 18 May.**

1. Absorb `data_update()` into `inst/extdata/source_all.R`. There isn't much to it right now, so I think we can remove the function wrapping around it and just throw the code into `source_all.R`.  
    * voting scheme :  -1 means leave it as is but document it and export it, +1 means absorb it as described above. If the sum of all our numbers exceeds 0, I'll do the proposed changes.
    * **CL vote: +1.0**
2.  Move `read.physical()` into `inst/extdata` and `source` it in each script that it's used. I do find it's kind of awkward to have a function in `inst/extdata`, but I also find it's awkward to load the package to build the data. Maybe we could create a new directory called `inst/extR`, is that a thing that is OK to do(?), and put it there then source it ? 
    * voting scheme :  -1 means leave it as is, +1 means move it. If the sum of all our numbers exceeds 0, I'll move it.
    * **CL vote: +0.25** and create new directory called `inst/extR`.

**Comment by casaultb** [comment]
As I expressed earlier I think the R/ folder should only include the core package functions. Functions to build the data should reside somewhere else as they are not intended for the end users but for the developers. I first noticed the issue with read.physical.R when I was trying to update the dataset but it wouldn't find the function unless the package was loaded - building the package should require the package to be loaded!

1- data_update.R
**BC vote:** +1

2- read.physical.R
**BC vote:** +1

Regarding the new home for read.physical.R: I like the idea of having a new folder inst/extdata/R to house all the .R files used to build the data. There would then be no need to have multiple folders such as inst/extdata/derived, .../zooplankton, .../phytoplankton, etc. The folder inst/extdata would then have two subfolders: csv and R.

**Comment by casaultb** [comment]
My interpretation is that files/folders in /inst are moved up to top-level folder upon installation. It is still ok to have inst/extdata/R which would be moved up to azmpdata/extdata/R in the installed version. This will not interfere with the azmpdata/R folder.
Here's the folders structure of my installed version:
C:\Users\casaultb\Documents\R\win-library\4.0\azmpdata\extdata  - which contains all the subfolders csv, derived, discrete,...
It is safe to have extdata/R there.
