### ISSUE TITLE
Allow user to not only get "nitrate" for example in area_indexer()

### ISSUE THREAD

**Issue by j-harbin** [casaultb/azmpdata#57]
This came up in our meeting today. For `area_indexer()`, if a user does the following:

```R
area_indexer(areanames="P5", doParameters = T, parameters="nitrate")
```

They **only** receive nitrate, but they may want integrated_nitrate_0_50 or integrated_nitrate_50_150, etc. Maybe a new argument to `area_indexer()` would be beneficial. Something like all=TRUE to allow for all parameters that exist.

**Comment by MMMcMahon** [comment]
This should be closed - it was resolved with the addition of `fuzzyParameters = TRUE` to area_indexer().  Now, entries in `parameter` can match all parameters matching the entered string(s).
