### ISSUE TITLE
PROPOSAL: Should be add a fuzzyParameters argument to plot_availability()

### ISSUE THREAD

**Issue by j-harbin** [casaultb/azmpdata#61]
This would be fairly simple to do because plot_availability() uses area_indexer(). This would mean the user would have the option of doing the following:

plot_availability(areaType="station", areaName="P5", parameters="nitrate", fuzzyParameters=T)

Which would make the availability plots for anything with the name nitrate in it found within P5. 

If we agree with this, I will add this in.

**Comment by MMMcMahon** [comment]
I agree - I set you an MS Teams message

**Comment by j-harbin** [comment]
This has been added by Mike and I fixed up the merging conflicts in mmm_dev branch. I'll therefore close this issue.
