### ISSUE TITLE
Easier access to RemoteSensing stations request

### ISSUE THREAD

**Issue by j-harbin** [casaultb/azmpdata#81]
Hi! I'm looking at the RemoteSensing_Weekly_Broadscale satellite measurements and I see they have 6 unique "areas" where they obtained the satellite data: "CS_remote_sensing"  "ESS_remote_sensing" "CSS_remote_sensing" "WSS_remote_sensing"
"GB_remote_sensing"  "LS_remote_sensing".

I see there is some mention of these polygon areas in azmpmap.R at ~ line 27-28. I was wondering if anyone would have time to add the polygon geometry to the RemoteSensing_Weekly_Broadscale data frame for easier access?

Thanks for the great package! It has been very useful.

**Comment by casaultb** [comment]
Hi Jamie. We have decided to removed the Remote Sensing datasets from azmpdata. The reason being that Remote Sensing data are accessible somewhere else through the PhytoFit Shiny app (e.g. https://cioosatlantic.ca/phytofit/). These datasets will be deleted in a future commit.

**Comment by j-harbin** [comment]
Thanks for the update! I'll close my issue.
